labs13-property-mgr/backend

package.json
=> Ethan baugher

data/migrations/20190606134844_create_properties_table.js, data/migrations/20190610172944_create_service_order_table.js, knexfile.js
=> Be eb wk2 d3 2

package.json
changed the dependencies but now it requires a whole new pr even though I had the same branch
=> addded dependency

api/routes/serviceRequest-router.js
=> service request end points finished

api/middleware/serversetup.js
=> service request file route changed

data/migrations/20190620095459_create_prop_images_table.js
=> prop image table added

api/models/tenant-model.js, api/routes/tenant-router.js
=> Fix tenant router for POST logic and model function find.

api/routes/tenant-router.js
=> Add a route to get tenant card by id.

api/routes/tenant-router.js
=> Ta backend tenant fix

api/models/tenant-model.js
=> Add delete and update methods to tenant model file, as there were none.

api/models/property-model.js, api/routes/property-router.js
=> Tenantsbyproperty backend Route and Model in Property-router.js and Property-model.js

api/models/property-model.js, api/routes/property-router.js
=> service by property id router created

api/models/tenant-model.js, api/routes/tenant-router.js
=> get service by tenant

data/migrations/20190610135812_tenant.js
Add notes field to tenant table.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Ready to review and merge
- [x ] My code follows the style guidelines of this project
=> Add notes field to tenant table.

api/models/property-model.js
=> Sorry Cori

api/models/property-model.js, api/routes/property-router.js
=> reverted get

api/models/service-model.js, api/routes/service-router.js, data/migrations/20190606134844_create_properties_table.js
=> Eb wk5d4 1

api/models/property-model.js
Add the image_url field to the findTenants() method in the property-model.js file
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts
=> Add the image_url field to the findTenants() method in the property-model.js file

data/migrations/20190606134844_create_properties_table.js
=> added more characters to image_url field in property table

api/firebase/functions/index.js, api/routes/property-router.js
=> editing error on property route

data/migrations/20190606134844_create_properties_table.js, knexfile.js
=> Bs updating property table

api/firebase/functions/index.js
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
=> fixed get request for images in storage

.env, .gitignore
=> Bs fixing env file

api/models/service-model.js, api/routes/property-router.js, api/routes/service-router.js
=> router and model adjusted

api/models/service-model.js, api/routes/property-router.js, api/routes/service-router.js
=> alphabetic change notes

data/migrations/20190610135812_tenant.js, data/migrations/20190610172944_create_service_order_table.js
tables for twilio functionality
- [X ] New feature (non-breaking change which adds functionality)
- [X ] Complete, ready to review and merge
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
=> Cori peck table updates for twilio

package.json, yarn.lock
moves dependencies
- [X ] Bug fix (non-breaking change which fixes an issue)
=> Cp fixing twilio and body parser

api/routes/property-router.js
=> property router changes

data/migrations/20190610135812_tenant.js, knexfile.js
=> Eb fixitfriday
